### ISSUE TITLE
Pre compiled version doesn’t install

### ISSUE THREAD

**Issue by Ijdtm7** [techtimefor/MultiMC-on-Arch-Linux-ARM-and-Manjaro-ARM#1]
Hey there. I am trying to use your precompiled version but when trying to install it says error could not open file multi mc-git... unrecognized Archive Format. I’m using manjaro arm. Got any ideas?

**Comment by techtimefor** [comment]
could be due to i did not update the system when i built it
Copy and paste this into your terminal and it should build

1 `cd $HOME/multimc-git && rm PKGBUILD && wget https://raw.githubusercontent.com/techtimefor/MultiMC-on-Arch-Linux-ARM-and-Manjaro-ARM/master/PKGBUILD `
2. Lastly do `makepkg -si`

**Tip** You cannot build packages from then AUR without the base-devel group `sudo pacman -S base-devel`

**Comment by techtimefor** [comment]
Hmm yeah seems like `wget` does not pull down the file properly [Click Here to Download Latest Version](https://github.com/techtimefor/MultiMC-on-Arch-Linux-ARM-and-Manjaro-ARM/blob/master/multimc-git-compiledbytechtimefor-14082020.tar.xz?raw=true) then save it to your Home directory open up terminal and run  `sudo pacman -U multimc-git-compiledbytechtimefor-14082020.tar.xz`

Hope this helps
